### ISSUE TITLE
"light-content" class assigned to dark background section

### ISSUE THREAD

**Issue by skydogtech** [maithemewp/mai-theme-engine#106]
Looks like the grid text may be inheriting?

![light-content](https://user-images.githubusercontent.com/6430858/31320421-5f546a5a-ac42-11e7-8963-5f1986b9d632.png)

**Comment by JiveDig** [comment]
@skydogtech do you, by any chance, have the grid shortcode you were using here?

**Comment by skydogtech** [comment]
`[grid content="page" columns="3" show="image, title, excerpt, more_link" content="page" parent="1690" exclude="289,120" order="asc" order_by="title"]`

**Comment by JiveDig** [comment]
Testing... but you have 2 "content" params in there ;)

**Comment by JiveDig** [comment]
`color: initial;` FTW.

**Comment by skydogtech** [comment]
Dang! That's great!

**Comment by JiveDig** [comment]
For sure. Just put this together to explain what I learned more 'deeply' today: https://codepen.io/JiveDig/pen/LmXbGP
