### ISSUE TITLE
image_size has no effect when parameter columns=1 is set. 

### ISSUE THREAD

**Issue by christiebizbudding** [maithemewp/mai-theme-engine#13]
Trying to change the image size to thumbnail but stays full width of column. 

[grid content="post" number="16" columns="1" show_date="true" show_author="true" image_size="thumbnail" show_content="true" content_limit="30" show_more_link="true"]

![screen shot 2017-05-18 at 10 47 16 am](https://cloud.githubusercontent.com/assets/25107329/26208153/65167ec0-3bb7-11e7-8ad7-ebc8ef62d766.png)

**Comment by JiveDig** [comment]
Right now there is CSS making the image width 100%. This will probably have to change in order to allow more layout options with the grid. I can remove that CSS too. The only issue is that without that CSS on some browser widths the image won't fill the full column, which is ugly.

**Comment by JiveDig** [comment]
@christiebizbudding your code above will still cause this issue, but you can fix by doing `image_align="center"`. It's a bit "quirky" but I think allows things to remain flexible.
