### ISSUE TITLE
Consider separate hooks/functions for banner title and banner content/excerpt

### ISSUE THREAD

**Issue by JiveDig** [maithemewp/mai-theme-engine#149]
Many people seem to want the title to display as normal, but the excerpt to remain in the banner.

**Comment by skydogtech** [comment]
Maybe you could add a set of options in customizer to 

- Remove title from banner area, but leave excerpt
- Remove excerpt from banner area, but leave title
- Remove both title and excerpt from the banner and restore them to content area

**Comment by JiveDig** [comment]
This is soooo much better now. Via https://github.com/maithemewp/mai-theme-engine/commit/84d8936c9cec50c6737882d55b721bca93480689

If you remove the excerpt/description from the banner area it will **_not_** display in the content area though. That could possibly be a feature in the future, but not now.

**Comment by JiveDig** [comment]
No customizer settings for this, but will consider when we do the big options rebuilt for more control per content type.
