### ISSUE TITLE
Logo not centering on Landing Page template?

### ISSUE THREAD

**Issue by JiveDig** [maithemewp/mai-theme-engine#187]
Saw this on 2 of our custom sites. Test/fix on clean install?

**Comment by dws122** [comment]
Tested on a clean install, and the logo DOES center on the landing page template.

**Comment by JiveDig** [comment]
Found it. Mai Ads & Extra Content uses `genesis_header_right` hook. Genesis checks if `has_action( 'genesis_header_right' )` and runs the header widget area stuff. I need to prevent that, probably in Mai Theme Engine.

**Comment by JiveDig** [comment]
Fixed in the next release, also manually patched the demo.
