### ISSUE TITLE
Character set not specified in HTTP headers

### ISSUE THREAD

**Issue by dws122** [maithemewp/mai-theme-engine#189]
instead of 
`Content-Type: text/html
`
use
`Content-Type: text/html; charset=utf-8
`

**Comment by JiveDig** [comment]
@dws122 Can you clarify here?

**Comment by dws122** [comment]
Sitebulb audit indicates that when defining the Content-Type we should also specify the default character set.

**Comment by JiveDig** [comment]
```
/**
 * HTML5 doctype markup.
 *
 * @since 2.0.0
 */
function genesis_html5_doctype() {
?>
<!DOCTYPE html>
<html <?php language_attributes( 'html' ); ?>>
<head <?php echo genesis_attr( 'head' ); ?>>
<meta charset="<?php bloginfo( 'charset' ); ?>" />
<?php
}
```

This is what G does now.

**Comment by JiveDig** [comment]
I'm gonna close this. For our custom projects we can use https://codex.wordpress.org/Plugin_API/Filter_Reference/bloginfo filter. I think we should stay away from this in our core product.
