### ISSUE TITLE
Manage dependencies using Composer  

### ISSUE THREAD

**Issue by timothyjensen** [maithemewp/mai-theme-engine#193]
Moving CMB2 and Plugin Update Checker to Composer dependencies will make it simpler to update these packages in the future.

**Comment by JiveDig** [comment]
My only issue with this is what happens during auto-install via the dependency script in the theme itself. Currently using https://github.com/afragen/wp-dependency-installer and may switch to MerlinWP when it's out of beta.

**Comment by timothyjensen** [comment]
Right. In most cases you don't want to commit the `vendor` directory just like you wouldn't want `node_modules` in your repo. But it this case we do want to commit the `vendor` directory because the plugin is being deployed to production sites without a build step.

The main advantage will be easier updates in the future: `composer update`. Also, with Composer set up you can easily add dev-dependencies (which you won't commit) like PHPUnit and PHPCS/WPCS when the time comes for that.

**Comment by JiveDig** [comment]
Doing this for CMB2 and Plugin Update Checker now. Thanks for helping me understand this all @timothyjensen! Composer is awesome.
