### ISSUE TITLE
Consider menu setting for when the mobile toggle kicks in

### ISSUE THREAD

**Issue by JiveDig** [maithemewp/mai-theme-engine#205]

**Comment by lionking1193** [comment]
Hello, 

When I look through google cache with HTML. My website duplicates menus between mobile and computer. I think it affects SEO. Can fix you it with a menu?
![screenshot_1](https://user-images.githubusercontent.com/24841398/46245626-0614fd00-c41b-11e8-998f-c2b591e9f203.png)

Thanks

**Comment by JiveDig** [comment]
Can you start a new issue? That is a new issue, unrelated to this one. Or use our actual support channels via https://support.maitheme.com

**Comment by JiveDig** [comment]
Another request for this via support.

**Comment by JiveDig** [comment]
![mai-mobile-menu-width](https://user-images.githubusercontent.com/540990/56383071-f1e1f300-61e6-11e9-8ad8-a06a9ed20603.png)
