### ISSUE TITLE
How to display the ‘Last Updated’ date?

### ISSUE THREAD

**Issue by ighosts22** [maithemewp/mai-theme-engine#220]
I regularly update my posts, so, how do I display the date of the update instead of the post date on the post info? The code I use on the old genesis topic does not work:

```
add_filter( 'genesis_post_info', 'os_post_info_filter' );
function os_post_info_filter($post_info) {
	if ( !is_page() ) {
	$post_info = '[post_modified_date before="Update: "] [post_author_posts_link] [post_comments]';
	return $post_info;
	}
}
```
Thanks!

**Comment by JiveDig** [comment]
hi there. For general support requests can you use our chat bubble at https://support.maitheme.com?

Your easiest solution is to use Genesis Simple Edits, but if you want to use code you may need to run it later. Run your filter in a function hooked into `after_setup_theme` like this:

```
add_action( 'after_setup_theme', function() {

     // Your code here:

});
