### ISSUE TITLE
Aspect ratio JS making things super tall randomly

### ISSUE THREAD

**Issue by JiveDig** [maithemewp/mai-theme-engine#225]
Can't really recreate this yet, but sometimes on first page load things look really stretched vertically.

@dws122  @christiebizbudding do you have screenshots still?

**Comment by christiebizbudding** [comment]
![the_collection___dr__will_cole_and_log_in_ _dr__will_cole_ _wordpress](https://user-images.githubusercontent.com/25107329/42348248-ba378dae-8076-11e8-81fa-87514d87ab60.png)

**Comment by JiveDig** [comment]
On maitheme.com (Incognito) I visit another page, then click logo to go back home and get this:

![screen shot 2018-07-05 at 5 13 52 pm](https://user-images.githubusercontent.com/540990/42348287-e05ddc40-8076-11e8-92bb-fef283080621.png)

Can anyone else recreate this? Using grid with image_align="bg" or col with image="some image ID here"
