### ISSUE TITLE
mai-theme-engine making invalid calls to GitHub

### ISSUE THREAD

**Issue by dws122** [maithemewp/mai-theme-engine#236]
This happens when visiting the plugins page and the system calls home to check for updates.

![plugins_ _bizbudding_inc__ _wordpress](https://user-images.githubusercontent.com/12969150/44530507-8a59bf00-a6bc-11e8-8d7c-dd983c2c6ba2.jpg)

**Comment by JiveDig** [comment]
Looks like it's only our add-ons doing that. I wonder why, since they are currently public repos. Is this only happening on sites that have the API key constant in wp-config? Or have you seen this elsewhere?

**Comment by JiveDig** [comment]
@dws122 Can you explain the steps to recreate this issue? I'm wondering if I can make it happen on my end.

**Comment by JiveDig** [comment]
Dave's reply via Slack

> use query monitor and visit plugins page to see calls

**Comment by JiveDig** [comment]
@dws122 Can you recall.... does everywhere this happen also use Wampum Programs? I think I found the issue.

**Comment by JiveDig** [comment]
This appears to be related to when we have a GH token set via a constant, not an actual issue in the engine plugin so closing this.
