### ISSUE TITLE
Banner when using section is bad.

### ISSUE THREAD

**Issue by lionking1193** [maithemewp/mai-theme-engine#240]
Hello, 

I am using shortcode on section of home page.
`[grid content="post" title_wrap="h2" show="image, title" number="3" align="center" order="asc"]`
It looks like the image parameters are not suitable for display. 

- Natural (350x263px)
- The image size shown is: 380 x 286px

Can you to fix it? I bought the license and everything seems to work very well except for the display image.

Thanks 
Sam

**Comment by lionking1193** [comment]
Hello,

I want to ask you: when I change the image size it affects the entire layout of the site?
I have accessed and modified the path: mai-theme-engine/mai-theme-engine.php

`				/**  Original Image Size
				'one-half' => array(
					'width'  => 550,
					'height' => 413,
					'crop'   => true, // 4x3
				),
					'one-third' => array(
					'width'  => 350,
					'height' => 263,
					'crop'   => true, // 4x3
				),*/
				
				'one-half' => array(
					'width'  => 585,
					'height' => 439,
					'crop'   => true, // 4x3
				),
				
				'one-third' => array(
				'width'  => 380,
				'height' => 286,
				'crop'   => true, // 4x3				
				),`
Thank you very much!

**Comment by JiveDig** [comment]
Okay, but don't edit anything in Mai Theme Engine, use the filter if you want to change the image sizes globally.
