### ISSUE TITLE
Using "hide the title" on page with banner

### ISSUE THREAD

**Issue by skydogtech** [maithemewp/mai-theme-engine#245]
causes the banner image to display full height

[https://cl.ly/ae85ddc4e3c3](url)

**Comment by JiveDig** [comment]
Do you happen to be using the 1.4.0 beta release here?

**Comment by skydogtech** [comment]
It’s Version 1.4.0-beta.19

Best,

Suzanne

---
Sky Dog Technologies
The GRAYCROSS Building
1072B Massachusetts Avenue
Arlington MA 02476
617 871-0550

**Comment by JiveDig** [comment]
Okay thought so, that banner image looks really tall (and we change the banner size in 1.4.0) ;)

**Comment by skydogtech** [comment]
I could def crop it down.. at one point it was for parallax setup

**Comment by JiveDig** [comment]
That is the new size though, so it works better with all the height settings. If you crop it, it will still try to pull the "banner" image size, not the crop you make.

**Comment by skydogtech** [comment]
oh yeah, right
