### ISSUE TITLE
Gradient screen resize issue

### ISSUE THREAD

**Issue by christiebizbudding** [maithemewp/mai-theme-engine#249]
Bottom of gradient on the banner doesn't reach the bottom of the section on screen resizing. Fixes on refresh.

[Screen Recording 2018-10-24 at 07.43 PM.mov.zip](https://github.com/maithemewp/mai-theme-engine/files/2512765/Screen.Recording.2018-10-24.at.07.43.PM.mov.zip)

**Comment by JiveDig** [comment]
@christiebizbudding Do you still see this anywhere?

**Comment by christiebizbudding** [comment]
@JiveDig no, haven't seen it in a long time.

**Comment by JiveDig** [comment]
TY. I think the change in how background images work fixed this. Gonna close this until it comes up again.
