### ISSUE TITLE
Duplicated product category description

### ISSUE THREAD

**Issue by lopwalj** [maithemewp/mai-theme-engine#252]
If you have defined your category description and the **Archive Intro Text** field is empty, the description is displayed twice on the front end.

In my case, I had the banner disabled on the Product taxonomies but something to consider is that if you have the Banner enabled, the description is also displayed in the banner area below the title and below the banner section. I think it shouldn't be displayed again.

**Comment by JiveDig** [comment]
Walter, this was a great find. Thanks! I couldn't recreate cause I always had content in both fields. I'll find a fix and add it to the next release.

**Comment by JiveDig** [comment]
This is still happening, or was re-introduced.

**Comment by JiveDig** [comment]
It only happens under these conditions:

1. Banner is disabled
2. ONLY add a description
3. Leave Intro Text empty
