### ISSUE TITLE
columns shortcode inside full-width section

### ISSUE THREAD

**Issue by skydogtech** [maithemewp/mai-theme-engine#269]
Using the sections template, I have this column configuration inside a section using all default **section settings**
```
[columns]
[col_one_twelfth][/col_one_twelfth]
[col_five_twelfths][/col_five_twelfths]
[col_one_half][/col_one_half]
[/columns]
```
The column content fits on one row as expected.

**However** when I change **section settings** so content width is "full-width," the last column wraps to a second row. All other column confgurations I can come up with work as expected at full-width (no wrapping). Can anyone reproduce?

**Comment by JiveDig** [comment]
Hmmm, this has to do with the padding added when you use col's in a full-width section:
```
.section .width-full .columns-shortcode > .col {
    padding: calc( 32px + 2vw );
}
```

**Comment by JiveDig** [comment]
Wow found a fix. David Browne FTW. https://codepen.io/anon/pen/KEVKNd

Gonna add this, after some testing:
```
.section .width-full > .columns-shortcode > .col:nth-last-of-type(2):first-of-type,
.section .width-full > .columns-shortcode > .col:nth-of-type(2):last-of-type {
	padding: calc( 32px + 2vw );
}
```
Then you won't need any extra code to "undo" it. This will only apply the padding when 2 columns are used as the immediate child in a full-width section.

**Comment by skydogtech** [comment]
sweet! David Browne, thanks man!

**Comment by JiveDig** [comment]
Well, while this is a really cool solution it looks like it's too much of a breaking change for existing sites. I'm going to have to revert. We have a few sites (including the Business theme) that use this layout, and can't break them with this change.

<img width="1348" alt="screenshot 2019-03-06 12 28 15" src="https://user-images.githubusercontent.com/540990/53900832-697b0a80-400b-11e9-8ca8-b48baafd7be8.png">

Looks like doing the layout you are after will require a little custom CSS still.

**Comment by skydogtech** [comment]
no worries
