### ISSUE TITLE
Error Boxed Container (After Entry Widgets and Comments Wrap)

### ISSUE THREAD

**Issue by lionking1193** [maithemewp/mai-theme-engine#274]
Hello, 

Would you please let me know how to fix it? You can look at the bottom of the page:
https://www.maryjanesandgaloshes.com/best-brother-sewing-machine/

![screenshot_3](https://user-images.githubusercontent.com/24841398/53294326-31a7e200-3817-11e9-98d3-3e2d4582c49c.png)

**Comment by JiveDig** [comment]
This is not anything I’ve seen before. I’m also not seeing it on your site on mobile, but I’ll check it out when I get to my comp.

**Comment by lionking1193** [comment]
Hello again,

Would you please let me know how to fix it?

**Comment by JiveDig** [comment]
Hi there, you have a widget in the After Entry widget area that is using floats. You can either convert to our grid shortcode there, or add some CSS to handle the overflow of floated elements.
```
.after-entry .widget {
    overflow: hidden;
}
```
