### ISSUE TITLE
Primary Menu isn't working when using sticky header style

### ISSUE THREAD

**Issue by lionking1193** [maithemewp/mai-theme-engine#299]
Hi, 

Please help me check Primary Menu isn't working when using a sticky header style.

![Screenshot_2](https://user-images.githubusercontent.com/24841398/61123003-6e762c00-a4cd-11e9-9cee-343d026bf09c.png)

Thank you very much!

**Comment by JiveDig** [comment]
Hi there, please ping is via our support @ https://support.maitheme.com.
