### ISSUE TITLE
Use 2 or 3 columns for submenus?

### ISSUE THREAD

**Issue by lionking1193** [maithemewp/mai-theme-engine#300]
Hi, 

How to use 2 or 3 columns for submenus? Like this: 
![Screenshot_3](https://user-images.githubusercontent.com/24841398/61123410-75ea0500-a4ce-11e9-8b58-3306c505323b.png)

I tried to customize it but didn't know where I should start. Can you help me with this issue? 
The image below is a submenu on my website.
![Screenshot_4](https://user-images.githubusercontent.com/24841398/61123575-ea24a880-a4ce-11e9-8cae-94b650bf0598.png)

Thank you very much.

**Comment by JiveDig** [comment]
Hi there, please ping us via support @ https://support.maitheme.com.
