### ISSUE TITLE
Add support for [footer_childtheme_link]?

### ISSUE THREAD

**Issue by skydogtech** [maithemewp/mai-theme-engine#307]
[Genesis shortcodes](https://studiopress.github.io/genesis/basics/genesis-shortcodes/#%5Bfooter_childtheme_link%5D)

**Comment by JiveDig** [comment]
With the new footer credits field in the Customizer this should already work?

**Comment by skydogtech** [comment]
hm, maybe I have the wrong shortcode:

https://d.pr/i/Be7R4q
https://d.pr/i/uFmbkb

it's coming up blank

**Comment by JiveDig** [comment]
That shortcode returns an actual URL. So it works if you do this:

`<a href="[footer_childtheme_link]">This</a>`
