### ISSUE TITLE
Setup Wizard should use theme name for the home page "Home - Reach Agency"

### ISSUE THREAD

**Issue by JiveDig** [maithemewp/mai-theme-engine#314]
When running the setup wizard and a page called "Home" already exists, it breaks things. The "old" home page is set as front page because the new home page is home-2 now.

If we change it to use "Home - Reach Agency" and check by title or slug, it will fix the issue, and be much better for importing different theme demos and not having multiple pages named "Home" in the back end.

**Comment by seothemes** [comment]
I think we should change it to Front Page, I've never seen anyone use the slug `front-page` before, and this is what it is actually used for. Makes it easier for us to maintain too.

**Comment by JiveDig** [comment]
The issue is more than that though. It needs something unique per-theme. The idea is that they can import 3 different demo homepages in a row (think Mai Solution) and it will work every time, and make sense when viewing Pages in the backend.

**Comment by JiveDig** [comment]
If they did it with “Front Page” they’d hit the same issue of front-page-2 gettin created and the wrong one being set as the front page.

**Comment by seothemes** [comment]
I'm wondering if we should leave them all as `home` in the theme demos, and add a step to the Demo Exporter which adds the theme name to the slug on export, e.g `home-reach-agency`. That eliminates human error, and ensures we always have the correct name scheme for the home page.

**Comment by seothemes** [comment]
Or we can just manually update the demos, and have a note somewhere to remind us to always use that naming scheme for the home page slug.

Either way it doesn't affect the setup wizard importer, as long as we always know what the slug is going to be.

**Comment by JiveDig** [comment]
I’m fine if we do it via the importer instead of relying on it being correct in the demos. 

I think it needs title and slug though, so when you look in the backend you don’t see multiple pages named “Home”.

**Comment by JiveDig** [comment]
Apparently I opened this on the old engine last night. Ugh.
