### ISSUE TITLE
“Not allowed to access this page” on genesis-getting-started when switching from a Mai theme

### ISSUE THREAD

**Issue by nickcernis** [maithemewp/mai-theme-engine#316]
1. Activate Mai Success.
2. Activate Genesis Sample from Appearance → Themes (or another theme that uses Genesis one-click theme setup).

You'll see “sorry you are not allowed to access this page” because Mai removes the Child Theme Setup page from the Genesis submenu.

It makes it look like the new theme is broken; it's not immediately clear that the cause is the previously active theme.

Once Mai Engine self-deactivates a visit to Genesis → Child Theme Setup works, but the user has to know to go there to complete set up their new theme.

**Comment by JiveDig** [comment]
Hey Nick, thanks for the report.

This repo is for our v1/Classic themes. Just confirming you're referring to Mai Success (our v2 theme) right? I can open a new issue on the new engine https://github.com/maithemewp/mai-engine/issues and test.

**Comment by JiveDig** [comment]
NP. I opened a [new issue here](https://github.com/maithemewp/mai-engine/issues/355).
