### ISSUE TITLE
hide feature image button dissapears

### ISSUE THREAD

**Issue by dws122** [maithemewp/mai-theme-engine#55]
the button to click to hide the featured image disappears after a featured image is uploaded

**Comment by JiveDig** [comment]
Wild, it removes the Crop Formats link too

**Comment by JiveDig** [comment]
I don't think i'm going to fix this for a while. It will take some serious extra work, probably loading the field via JS on click. If anyone opens support for this we'll just have to direct them to save first, so the field shows up.

Basically, the WP JS removes all the HTML when adding/removing the image in the metabox.

**Comment by JiveDig** [comment]
Not only does it disappear, but if it's already checked (to hide) and you change the featured image, it saves as unchecked because the field doesn't even get submitted. So, need to do an isset() check or something.

Fix that!

**Comment by JiveDig** [comment]
Okay, settings are retained at least. Still weird with the checkbox disappearing cause the aggressive featured image JS.
